repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    -   id: ruff

-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        args: [ "-m", "not skip_this" ]
        language: system
        pass_filenames: false
        always_run: true
