# config options for the app. This should be published in the repo
# only place public info here. Private and secrets should be in the .env file
IMAGE:
  WIDTH: 224
  HEIGHT: 224
  CHANNELS: 3


TRAINING:
  BATCH_SIZE: 32

ENCODER:
  PATCH_SIZE: 16




